---
title: "KRATOZZ-BLOGS"
date: 2018-07-07
---

title: Kratozz Blogs
author: Kratozz_
email: helloworld@gmail.com
description: > # this means to ignore newlines until "baseurl:"
First Blog/website that i have setup

# social links
twitter_username: @Unleash
github_username:  Kratozz_

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
