title: Kratozz Blogs
author: Kratozz_
email: helloworld@gmail.com
description: First Blog/website that i have setup


twitter_username: @Unleash
github_username:  Kratozz_

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
